---
title: "Personality Tests"
author: "Eddie & Miguel"
date: "10/16/2018"
output: html_document
css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{R}
library(data.table)
library(tidyverse)
library(data.table)
load("~/Downloads/data/USdata.RData")
load("~/Downloads/data/USage.RData")
```

```
USdata <- filter(data, country == 'US')
USage <- filter(USdata, age < 100)
```

<div class="titles">Personality Tests DataSource/Bibliography</div>

<br>

<div class="link_citing">
  “Assessment & Selection Other Assessment Methods.” 
  *U.S. Office of Personnel Management*, 2018,
  https://www.opm.gov/policy-data-oversight/assessment-and-selection/other-assessment-methods/personality-tests/.
</div>

We chose to use this article in our bibliography/data source because it contains crucial insight on the personality traits most frequently assessed in work situations. This article argues that it is ill-advised to use a measure that taps only on one specific dimension. Instead, job performance outcomes are best predicted by a combination of personality measures. We find this interesting because it is a reference that can lead us to further research on personality tests. This article can help us formulate our argument against the weapon of math destruction that is the personality test. 

<br>

<div class="link_citing">
  “Big Five Personality Test Traits.” 
  *123test*, 10 Sept. 2018, 
  https://www.123test.com/big-five-personality-theory/.
</div>

This website describes how in a personality test the Five Factor Model (FFM) and the global factors of personality may also be used to reference the Big Five traits. We chose this source because every personality trait is broken down and defined clearly. The Big Five traits are even visually explained through the use of diagrams. 

<br>

<div class="link_citing">
  Martin, Whitney. “The Problem with Using Personality Tests for Hiring.” 
  *Harvard Business Review*, 6 Dec. 2017, 
  https://hbr.org/2014/08/the-problem-with-using-personality-tests-for-hiring.
</div>

This article from the Harvard Business Review demonstrates the most effective hiring selection practices and those that don’t work well. We chose this article because there is a diagram that shows the most effective hiring selection practices based on validity coefficients ranging from 0 to 1. The higher the number, the higher the correlation between test scores and predicted job performance. The results show that personality tests have a lower correlation. This article has valuable information that helps us understand which hiring processes use the most effective measures when predicting job performance. 

<br>

<div class="link_citing">
  “Open Psychology Data: Raw Data from Online Personality Tests.” 
  *MACH-IV: Machiavellianism Test*, Open Source Psychometrics Project, 
  https://openpsychometrics.org/_rawdata/. 
</div>

We chose this data source because it provides multiple collections of raw data from online personality tests taken by real people from different regions internationally. The data collections also contain data from test takers ranging from a variety of different age groups. This data will be used in order to compare the personality types most attributed to different job roles. Additionally, we are able to see the similarities and differences within the questions asked to the test takers and see how their answers affect the results of the tests.

<br>

<div class="link_citing">
  Schmitt, David, et al. “The Geographic Distribution of Big Five Personality Traits Patterns and Profiles of Human Self-Description Across 56 Nations.”, vol. 38, no. 2, Mar. 2007, 
  https://www.researchgate.net/publication/230766917_The_geographic_distribution_of_Big_Five_personality_traits.
</div>

This article contains numerous figures and an ample amount of data on the Big 5 personality traits patterns across 56 different nations. Schmitt et al. even mention problems in comparing personality trait scores across cultures. This source will be helpful when comparing our data because this article has previous large-scale studies of personality traits across cultures. The authors successfully explain what the “Big Five” traits of human personality are and how they are used in personality tests. 

<br>

<div class="titles"> Data Exploration</div>

<p>We decided to focus soley on the US demographic of the data
   
   Then we decided to breakdown that data further and create
   histograms to seperate the data by: 
   
   - Gender
   - Race
   - Age</p>
   
<div class="headers">1 Dimensional Data Exploration</div>
   
<div class="headers">Gender</div>
   
```{R}
ggplot(data = USdata) + 
  geom_bar(mapping = aes(x = gender, fill = gender)) + scale_x_continuous(
    breaks = c(0,1,2,3),
    label = c("Missed", "Men", "Women", "Other")) +
    labs(title = "Bar Chart",
         subtitle = "Gender Distribution of BIG5 Test Takers (US)",
         caption="Source: https://openpsychometrics.org/_rawdata/")
```

<p>This graph shows the different genders the personality test takers identified themselves as. Genders included men, women and other. This information is important because it demonstrates how diverse the measure of the Big-Five personality traits turned out based on the gender of the participants.</p>

<br>

<div class="headers">Age</div>

```{R}
ggplot(data = USage) +
  geom_bar(mapping = aes(x = age)) +
    labs(title = "Bar Chart",
         subtitle = "Age Distribution of BIG5 Test Takers (US)",
         caption="Source: https://openpsychometrics.org/_rawdata/")
```

<p>This graph tells us how old the personality test takers of the Big-Five personality traits are in comparison to the total amount of the participants. Immediately, we notice the majority of personality test takers fall between the ages of 13 and 25. The result of having a lot of young people who took this personality test could be because between the ages of 13 and 25, young adults are in need and applying for jobs. For instance, many undergraduate students start applying for internships and full-time positions. </p>

```{R}
ageBreaks <- c(13, 18, 30, 40, 50, 60, 70, 80, 90, 100)
ageLabels <- c("13-18", "18-30", "30-40", "40-50", "50-60", "60-70", "70-80", "80-90", "90+")

setDT(USage)[ , agegroups := cut (age,
                                  breaks = ageBreaks,
                                  right = FALSE,
                                  labels = ageLabels)]
```

```{R}
ggplot(data = USage) +
  geom_bar(mapping = aes(x = agegroups)) +
  labs(title = "Bar Chart",
      subtitle = "Age (Seperated by buckets) distribution of BIG5 Test Takers (US)",
      caption="Source: https://openpsychometrics.org/_rawdata/")
```

<br>

<div class="headers">Race</div>

```{R}
ggplot(data = USdata) +
  geom_bar(mapping = aes(x = race, fill = race)) + scale_x_continuous(
    breaks = c(0,1,2,3,4,5,6,7,8,9,10,11,12,13),
    label = c("Missed",
              "Mixed Race", 
              "Artic (Siberian, Eskimo)", 
              "Caucasian (European)", 
              "Caucasian (Indian)",
              "Caucasian (Middle East)",
              "Caucasian (North African, Other)",
              "Indigenous Australian",
              "Native American",
              "North East Asian (Mongol, Tibetan, Korean Japanese, etc)",
              "Pacific (Polynesian, Micronesian, etc)",
              "South East Asian (Chinese, Thai, Malay, Filipino, etc)",
              "West African, Bushmen, Ethiopian",
              "Other")
  ) + coord_flip() + 
    labs(title = "Bar Chart",
         subtitle = "Race Distribution of BIG5 Test Takers (US)",
         caption="Source: https://openpsychometrics.org/_rawdata/")
```
<p>The race in which the personality test takers identified themselves as is shown by this graph. The top three race categories that stand out include Caucasian (European), Other and Mixed Race. A reason why the categories "Other" and "Mixed Race" have a high count could be because ethnicities such as Hispanic is not considered a race under the Census Bureau. Federal policy defines "Hispanic" not as a race, but as an ethnicity. This type of case also applies to other ethnicities in the United States.</p> 



   


